[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
toolbarMode = "minimal"

[server]
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"
base = "dark"

